export const APPLY_PROPS = 'APPLY_PROPS';
//TOGGLE
export const TOGGLE = 'TOGGLE';
//MENU
export const APPLY_MENU = 'APPLY_MENU';
//MOREMENU
export const MERGE_MENUS = 'MERGE_MENUS';
export const SET_MOREMENU = 'SET_MOREMENU';
//SET_VIEWPORT_MOBILE (Mobile detector)
export const SET_VIEWPORT_MOBILE = 'SET_VIEWPORT_MOBILE';
//FETCHES
export const FETCH_MENU = 'FETCH_MENU';
export const FETCH_PROPS = 'FETCH_PROPS';
//EVENT LISTENER
export const ADD_EVENTS_LISTENER = 'ADD_EVENTS_LISTENER';
export const REMOVE_EVENTS_LISTENER = 'REMOVE_EVENTS_LISTENER';
// TEASERS
export const FETCH_TEASERS= 'FETCH_TEASERS';
